version: '2.34.0'

services:
  auth-api-database:
    container_name: auth-api-mongo-db
    image: mongo:8.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    networks:
      - bridge-network-auth-api
    restart: always

  auth-api-cache:
    container_name: auth-api-cache-redis
    image: redis:latest
    networks:
      - bridge-network-auth-api
    restart: always
    volumes:
      - redis-data:/data

  auth-api:
    container_name: auth-api
    image: lorisslvd/auth-api:latest
    pull_policy: always
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - bridge-network-auth-api
    restart: always

networks:
  bridge-network-auth-api:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  mongo-configdb: