spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/auth_db}

    redis:
      timeout: 60000
      url: ${REDIS_URL:redis://localhost:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com

twilio:
  account_sid: ${TWILIO_ACCOUNT_SSID}
  auth_token: ${TWILIO_AUTH_TOKEN}
  phone_number: ${TWILIO_PHONE_NUMBER}


jwt:
  access_token_secret_key: ${TOKEN_SECRET_KEY}
  access_token_expiration: 3600
  refresh_token_secret_key: ${REFRESH_TOKEN_SECRET_KEY}
  refresh_token_expiration: 2592000
